include:
  - /apps/auth/docker-compose.yml
  # path:
  #   - /apps/auth/docker-compose.yml
services:
  todo_postgres:
    container_name: todo_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_main:/var/lib/postgresql/data
    ports:
      - '5430:5432'
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    restart: always
volumes:
  pg_main:
  pgadmin:
networks:
  postgres:
    driver: bridge
