services:
  auth_postgres:
    container_name: auth_postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_AUTH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_AUTH_DB}
    volumes:
      - pg_auth:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    networks:
      - postgres
    restart: always

  # pgadmin:
  #   container_name: auth_pga
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  #   volumes:
  #     - pga_auth:/var/lib/pgadmin
  #   ports:
  #     - '5051:80'
  #   restart: always
volumes:
  pg_auth:
  pga_auth:
networks:
  postgres:
    driver: bridge
